version: '3'

services:

  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master      
    volumes: 
      - /spark
      - ./zeppelin/data:/zeppelin/data 
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - zeppelin-spark-standalone


  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    volumes: 
      - ./zeppelin/data:/zeppelin/data 
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - zeppelin-spark-standalone



  zeppelin-spark: 
    image: apache/zeppelin:0.9.0
    container_name: zeppelin-spark
    ports: 
      - "8079:8080"
    volumes: 
      - ./zeppelin/logs:/zeppelin/logs
      - ./zeppelin/notebook:/zeppelin/notebook
      - ./zeppelin/data:/zeppelin/data
    volumes_from: 
      - spark-master:ro
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/spark"
    networks:
      - zeppelin-spark-standalone


networks: 
  zeppelin-spark-standalone: